#!/bin/sh

msg_file="$1"
pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?: .+$"

if ! grep -qE "$pattern" "$msg_file"; then
  echo "[error] Invalid commit message pattern!"
  echo "Example of a valid message:: feat(api): adding users endpoint"
  exit 1
fi
